---
- name: Deploy for Debian system
  include: web_deb.yaml
  when: ansible_os_family == 'Debian'

- name: Deploy for RedHat system
  include: web_rh.yaml
  when: ansible_os_family == 'RedHat'


- name: 1st directory creating
  file:
    path: "{{ default_home }}"
    state: directory

- name: 2nd directory creating
  file:
    path: "{{ default_home2 }}"
    state: directory

- name: 1st index page creating
  template:
    src: index.j2
    dest: "{{ default_home }}/index.html"
    backup: no
  tags:
    - indx_template

- name: 2nd index page creating
  template:
    src: index.j2
    dest: "{{ default_home2 }}/index.html"
    backup: no
  tags:
    - indx2_template

- name: TemplatesConfig
  template:
    src: vhosts.j2
    dest: "{{ nginx_cfg }}/vhost_{{ hostvars[inventory_hostname].ansible_hostname }}.conf"
    backup: no
  become: yes
  tags:
    - config_template

- name: TemplateHostsFile
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    backup: no
  become: yes
  tags:
    - hosts_template

- name: NGINX restarting
  service:
    name: nginx
    state: restarted

- name: Connection to site checking
  wait_for:
    host: "{{ hostvars[inventory_hostname].ansible_hostname }}.site"
    port: 80
    state: started
    timeout: 7
  tags:
    - test_tcp

- name: Sites content checking
  uri:
    url: "http://{{ hostvars[inventory_hostname].ansible_hostname }}.site"
    return_content: yes
  register: this
  failed_when: "'comrates' not in this.content "
  tags:
    - indx_page_test
- debug:
    msg: "{{ this.status }}"
  tags:
    - http_code_test
