---
- name: Add EPEL repository
  yum:
    name: epel-release
    state: present

- name: NGINX. Install packages
  yum:
    name: "{{ yum_web_packages }}"
    state: present

- name: NGINX. Remove welcome file
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent

- name: NGINX. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes
